---
title: "M4Q3"
author: "Taylor Rogers"
date: '2022-06-09'
output: html_document
---

```{r}
#install.packages("rattle")

library(tidyverse)
library(tidymodels)
library(caret)
library(rpart)
library(rpart.plot)
library(rattle)
library(RColorBrewer)
```

```{r}
heart = read_csv("heart_disease-1.csv")
summary(heart)
```

```{r}
heart = heart %>%
  mutate(Sex = as_factor(Sex)) %>%
  mutate(ChestPainType = as_factor(ChestPainType)) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as_factor(ST_Slope)) %>%
  mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = fct_recode(HeartDisease, "No"="0", "Yes"="1"))
```

```{r}
set.seed(12345)
heart_split = initial_split(heart, prop=0.70, strata = HeartDisease)
train = training(heart_split)
test = testing(heart_split)
```

```{r}
heart_recipe = recipe(HeartDisease ~ Age + Sex + ChestPainType + RestingBP + Cholesterol + FastingBS + RestingECG + MaxHR + ExerciseAngina + Oldpeak + ST_Slope, train)

heart_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

heart_wflow = 
  workflow() %>% 
  add_model(heart_model) %>% 
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)
```

```{r}
#look at the tree's fit
heart_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")  
```
```{r}
#extract the tree's fit from the fit object
tree = heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

#plot the tree
rpart.plot(tree)
```
```{r}
#alternative
fancyRpartPlot(tree) 
```
###Question 2: ST_Slope 

Look at the "rpart" complexity parameter "cp".    
```{r}
heart_fit$fit$fit$fit$cptable
```

###Question 3: 0.017  ???

```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```



```{r}
heart_recipe = recipe(HeartDisease ~., train) %>% 
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

tree_grid = expand.grid(cost_complexity = seq(0.001,0.1,by=0.001))

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

tree_res = 
  heart_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```
```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```
###Question 4: 0.846 NO  .78?
###Question 5: 0.0075


```{r}
final_wf = 
  heart_wflow %>% 
  finalize_workflow(best_tree)
```

```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5) 

```

```{r}
rpart.plot(tree)
```

###Question 6: Yes

```{r}
heartpred = predict(final_fit, train, type = "class")
head(heartpred)
```
```{r}
confusionMatrix(heartpred$.pred_class,train$HeartDisease,positive="Yes") #predictions first then actual
```

```{r}
heartpred_test = predict(final_fit, test, type = "class")
head(heartpred_test)
```

Caret confusion matrix and accuracy, etc. calcs  
```{r}
confusionMatrix(heartpred_test$.pred_class,test$HeartDisease,positive="Yes") #predictions first then actual
```

###Question 7: .8754
###Question 8:.9239
###Question 9:.5530
###Question 10:  .8478